# https://github.com/marketplace/actions/github-action-for-firebase

name: Build and Deploy submissions
on:
  push:
    branches:
      - main
    paths:
      - 'submissions/**'
  pull_request:
    branches:
      - dev
      - staging
    paths:
      - 'submissions/**'

jobs:
  build:
    name: Build and deploy submissions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: submissions/functions
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "PROJECT_ID=personal-349320" >> "$GITHUB_ENV"
              eval "echo \"$(cat .firebaserc.template)\"" > .firebaserc
          else
              echo "PROJECT_ID=personal-349320" >> "$GITHUB_ENV"
              eval "echo \"$(cat .firebaserc.template)\"" > .firebaserc
          fi
      - name: Create props files
        env:
          CAPTCHA_SECRET: ${{secrets.CAPTCHA_SECRET}}
        run: |
          eval "echo \"$(cat secrets.js.template)\"" > secrets.js
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.2'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:submissions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: 'submissions'
